#!/bin/bash

case "$1" in
    configure)
      if [[ ! -e "/usr/bin/hzn" ]]; then
        ln -s /usr/horizon/bin/hzn /usr/bin/hzn
      fi
      if [[ ! -e "/usr/bin/horizon-container" ]]; then
        ln -s /usr/horizon/bin/horizon-container /usr/bin/horizon-container
      fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
      echo "postinst called with unknown argument \`$1'" >&2
      exit 1
    ;;
esac

exit 0
