#!/bin/bash

set -x

# This shell script requires 6 env vars to be set before calling it.
# AGBOTUSER - the horizon exchange user that owns this agbot
# AGBOTPW - the horizon exchange user's password
# AGBOTID - an identifier (string) that uniquely identifies the agbot
# AGBOTNAME - a display name for this agbot
# EXCHANGEURL - the URL to the exchange that you want to work with

if [ "$AGBOTUSER" = "" ]
then
    echo "MUST specify AGBOTUSER"
    exit 1
fi

if [ "$AGBOTPW" = "" ]
then
    echo "MUST specify AGBOTPW"
fi

if [ "$AGBOTID" = "" ]
then
    echo "MUST specify AGBOTID"
fi

if [ "$AGBOTTOKEN" = "" ]
then
    echo "MUST specify AGBOTTOKEN"
fi

if [ "$AGBOTNAME" = "" ]
then
    echo "MUST specify AGBOTNAME"
fi

if [ "$EXCHANGEURL" = "" ]
then
    echo "MUST specify EXCHANGEURL"
fi

echo "Creating Agbot user..."
CR8USER=$(curl -sLX PUT --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"password":"'${AGBOTPW}'","email":"me@gmail.com"}' ${EXCHANGEURL}'users/'${AGBOTUSER} | jq -r '.msg')
echo $CR8USER

echo "Registering Agbot instance..."
REGAGBOT1=$(curl -sLX PUT --header 'Content-Type: application/json' --header 'Accept: application/json' -H "Authorization:Basic ${AGBOTUSER}:${AGBOTPW}" -d '{"token":"'${AGBOTTOKEN}'","name":"'${AGBOTNAME}'","msgEndPoint":""}' ${EXCHANGEURL}'agbots/'${AGBOTID} | jq -r '.msg')
echo "$REGAGBOT1"
