#!/bin/bash

DOCKER_ENGINE=docker   # Default to docker
command -v docker >/dev/null 2>&1
rc=$?
if [[ $rc -ne 0 ]]; then
    command -v podman >/dev/null 2>&1
    rc=$?
    if [[ $rc -eq 0 ]]; then
        DOCKER_ENGINE="podman"
    fi
fi

if [ "$1" == "remove" ] || [ "$1" == "purge" ]; then

  # remove all running containers with horizon tags
  containers="$(${DOCKER_ENGINE} ps -aq 2> /dev/null)"
  if [ "$containers" != "" ]; then
    # TODO: add infrastructure labels too
    # reassign containers variable after doing some filtering
    containers=$(echo $containers | xargs ${DOCKER_ENGINE} inspect | jq -r '.[] | select ((.Config.Labels | length != 0) and (.Config.Labels["openhorizon.anax.service_name"] !="" or .Config.Labels["openhorizon.anax.infrastructure"] != ""))')
  fi

  # TODO: deal with no container output
  # remove running containers
  if [ "$containers" != "" ]; then
    echo $containers | jq -r '.Id' | xargs ${DOCKER_ENGINE} rm -f
  fi

    # remove networks; some errors are expected b/c we're issuing remove command for even networks that should have already been removed by anax
    cat /var/horizon/prerm.bridges <(echo $containers | jq -r '.NetworkSettings.Networks | keys[]') | sort | uniq | grep -v 'bridge' | xargs ${DOCKER_ENGINE} network rm 2> /dev/null

    # remove container images; TODO: use labels to remove infrastructure container images too once they are tagged properly upon
    cat /var/horizon/prerm.images <(echo $containers | jq -r '.Config.Image') | sort | uniq | xargs ${DOCKER_ENGINE} rmi 2> /dev/null
fi

if [ "$1" == "purge" ]; then

  rm -Rf /etc/horizon /var/cache/horizon /etc/default/horizon /var/tmp/horizon /var/run/horizon

  # remove all content from /var/horizon that isn't related to the dedicated SBC images
  find /var/horizon -mindepth 1 ! \( -name '.firstboot' -or -name 'image_version' \) -exec rm -rf {} +
  if [ "$(ls -A /var/horizon)" ]; then
    rmdir /var/horizon
  fi
fi

exit 0
