#!/bin/bash

if [[ ! -f /etc/default/horizon ]]; then
    # Only create an empty/template file if they do not already have a real one
    mkdir -p /etc/default
    echo -e "HZN_EXCHANGE_URL=\nHZN_FSS_CSSURL=\nHZN_MGMT_HUB_CERT_PATH=\nHZN_DEVICE_ID=\nHZN_AGENT_PORT=8510" > /etc/default/horizon
    # Note: postrm deletes this file in the purge case
fi

systemctl daemon-reload
systemctl enable horizon.service
if systemctl --quiet is-active horizon.service; then
	systemctl stop horizon.service   # in case this was an update
fi

mkdir -p /var/horizon
mkdir -p /var/run/horizon

systemctl start horizon.service

exit 0
