#!/bin/bash

agent_port_varname="HZN_AGENT_PORT"
default_port="8510"

if [ "$1" == "" ]; then
  (>&2 echo "Missing required first argument configuration file path")
  exit 1
fi

var_filepath="$1"

# make sure to avoid matching windows line endings
existing_agent_port=$(grep -oP "${agent_port_varname}=\K([^\r\n^M]+)" $var_filepath)

# If the HZN_AGENT_PORT variable is present but not set to a value, then use sed to set the
# variable to its default value. If the variable is not present at all, then use sed to append
# a line with the default value.

if [ "$existing_agent_port" == "" ]; then
  anaxPort=$(grep $agent_port_varname $var_filepath)
  if [ "$anaxPort" != "" ]; then
    systemd-cat -t horizon-set-agent-port echo "Setting ${agent_port_varname} in $var_filepath to $default_port"
    sed -i "s,${agent_port_varname}=,${agent_port_varname}=${default_port}," $var_filepath
  else
    systemd-cat -t horizon-set-agent-port echo "Setting ${agent_port_varname} in $var_filepath to $default_port"
    sed -i "$ a ${agent_port_varname}=$default_port" $var_filepath
  fi
fi