#!/bin/bash -e

if [[ ! -d "$1" ]]; then
  (>&2 echo "Missing required first argument (base directory path) or provided arg doesn't name a directory")
  exit 1
fi

# ephemeral and config
mkdir -p $1/var/{horizon/,run/horizon/}
mkdir -p $1/etc/{default/,horizon/}
mkdir -p $1/etc/horizon/{policy.d,agbot/policy.d/,trust/}

if [[ "$2" != "EPHEMERAL_ONLY" ]]; then
  mkdir -p $1/usr/horizon/{bin/,sbin/,web/}
fi
