// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package i18n_messages

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p := messageKeyToIndex[key]
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"de":    &dictionary{index: deIndex, data: deData},
		"en":    &dictionary{index: enIndex, data: enData},
		"es":    &dictionary{index: esIndex, data: esData},
		"fr":    &dictionary{index: frIndex, data: frData},
		"it":    &dictionary{index: itIndex, data: itData},
		"ja":    &dictionary{index: jaIndex, data: jaData},
		"ko":    &dictionary{index: koIndex, data: koData},
		"pt_BR": &dictionary{index: pt_BRIndex, data: pt_BRData},
		"zh_CN": &dictionary{index: zh_CNIndex, data: zh_CNData},
		"zh_TW": &dictionary{index: zh_TWIndex, data: zh_TWData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"Agreement %v already exists, ignoring proposal: %v":                                                                       147,
	"Agreement for %v no longer valid on the agbot. Node will cancel it.":                                                      77,
	"Agreement reached for service %v. The agreement id is %v.":                                                                76,
	"Comparison operator: %v is not supported for boolean value: %v":                                                           131,
	"Comparison operator: %v is not supported for numeric value: %v":                                                           130,
	"Comparison operator: %v is not supported for single version: %v":                                                          134,
	"Comparison operator: %v is not supported for string list value: %v":                                                       132,
	"Comparison operator: %v is not supported for string value: %v":                                                            133,
	"Comparison operator: %v is not supported for version expression: %v":                                                      135,
	"Complete changing service configuration state to %v for %v for the node.":                                                 53,
	"Complete cleaning up the service instance %v.":                                                                            95,
	"Complete downgrading service %v/%v from version %v to version %v.":                                                        115,
	"Complete node configuration/registration for node %v.":                                                                    37,
	"Complete node update for %v.":                                                                                             21,
	"Complete policy advertising with the exchange for service %v/%v.":                                                         169,
	"Complete service auto configuration for %v/%v.":                                                                           48,
	"Complete service configuration for %v/%v.":                                                                                47,
	"Complete starting agreement-less service %v/%v and its dependents.":                                                       103,
	"Complete terminating agreement for %v. Termination reason: %v":                                                            79,
	"Complete upgrading service %v/%v from version %v to version %v.":                                                          109,
	"Could not find lower version to downgrade for %v/%v version %v.":                                                          117,
	"Deleted all node user input":                                                                                              44,
	"Deleted node policy":                                                                                                      41,
	"Deployment config %v contains unsupported bind for %v, %v":                                                                185,
	"Deployment config %v contains unsupported bind for a workload, %v":                                                        184,
	"Deployment config %v contains unsupported capability for a workload":                                                      182,
	"Deployment config %v contains unsupported capability for infrastructure container.":                                       183,
	"Encountered error for AgreementVerification for %v with agbot, error %v":                                                  81,
	"Encountered error starting dependen services for %v/%v. %v":                                                               97,
	"Error Unmarshalling deployment override string %v for agreement %v, error: %v":                                            187,
	"Error Unmarshalling deployment string %v, error: %v":                                                                      186,
	"Error changing service configstate %v, error %v":                                                                          51,
	"Error cleaning up old containers before starting up new containers for %v. Error: %v":                                     191,
	"Error configuring service %v. %v":                                                                                         50,
	"Error converting the selections into Selectors: %v":                                                                       54,
	"Error deleting agreement for %v in exchange: %v. Will retry.":                                                             80,
	"Error downgrading service %v/%v from version %v to version %v. Eror: %v":                                                  118,
	"Error downgrading service %v/%v version %v. %v":                                                                           119,
	"Error finding the new service definition to downgrade to for %v/%v version %v key %v. error: %v":                          116,
	"Error getting %v for output, error %v":                                                                                    1,
	"Error getting all the services from agreements: %v":                                                                       101,
	"Error getting service definitions %v from db. %v":                                                                         62,
	"Error getting service instance %v from db. %v":                                                                            66,
	"Error getting service references for pattern %v. %v":                                                                      39,
	"Error handling Cancel message for %v. %v":                                                                                 90,
	"Error handling Cancel message. %v":                                                                                        91,
	"Error handling DataReceived message for %v. %v":                                                                           86,
	"Error handling DataReceived message. %v":                                                                                  87,
	"Error handling MeterNotification message for %v. %v":                                                                      88,
	"Error handling MeterNotification message. %v":                                                                             89,
	"Error handling ReplyAck message for %v. %v":                                                                               84,
	"Error handling ReplyAck message. %v":                                                                                      85,
	"Error handling proposal for service %v/%v. Error: %v":                                                                     151,
	"Error in creating or replacing node policy. %v":                                                                           13,
	"Error in deleting node policy. %v":                                                                                        15,
	"Error in deleting node userinput. %v":                                                                                     18,
	"Error in node configuration. The node is not found from the database.":                                                    31,
	"Error in node configuration. The node must be in 'configured' or 'configuring' state in order to change the state to %v.": 32,
	"Error in node configuration/registration for node %v. %v":                                                                 9,
	"Error in node unregistration. %v":                                                                                         11,
	"Error in patching node policy. %v":                                                                                        14,
	"Error in patching node user input. %v":                                                                                    17,
	"Error in service configuration for %v. %v":                                                                                38,
	"Error in updating node %v. %v":                                                                                            10,
	"Error in updating node user input. %v":                                                                                    16,
	"Error loading image for %v/%v.":                                                                                           73,
	"Error loading image for service %v/%v.":                                                                                   74,
	"Error marking agreement %v terminated in database: %v.":                                                                   61,
	"Error parsing input for node configuration/registration. Input body couldn't be deserialized to configstate object: %v, error: %v":            3,
	"Error parsing input for node configuration/registration. Input body couldn't be deserialized to node object: %v, error: %v":                   2,
	"Error parsing input for node policy patch. Input body could not be deserialized into a Constraint Expression or Property List: %v, error: %v": 6,
	"Error parsing input for node policy patch. Input body did not contain a Constraint Expression or Property List: %v, error: %v":                7,
	"Error parsing input for node policy. Input body could not be deserialized as a policy object: %v, error: %v":                                  5,
	"Error parsing input for node update. Input body couldn't be deserialized to node object: %v, error: %v":                                       4,
	"Error parsing input for node user input. Input body could not be deserialized as a UserInput object: %v, error: %v":                           8,
	"Error parsing the selections %v. %v":                                                                                             0,
	"Error restarting containers for agreements %v: %v":                                                                               190,
	"Error retrieving agreement %v from database, error %v":                                                                           55,
	"Error retrieving all service instances from database for %v. %v":                                                                 64,
	"Error retrieving all service instances from database, error: %v":                                                                 65,
	"Error retrieving all service instances from datavase for %v/%v version %v key %v. %v":                                            63,
	"Error retrieving matching agreements from database for workloads %v. Error: %v":                                                  67,
	"Error retrieving node %v from the exchange: %v":                                                                                  69,
	"Error saving new node config state (unconfiguring) in the database: %v":                                                          30,
	"Error saving new node config state to database: %v":                                                                              36,
	"Error starting containers for agreement %v: %v":                                                                                  189,
	"Error starting containers: %v":                                                                                                   188,
	"Error starting dependen service %v/%v version %v for agreement %v. %v":                                                           98,
	"Error starting service %v/%v version %v, error: %v":                                                                              100,
	"Error unregistring the node. The node is not found from the database.":                                                           24,
	"Error unregistring the node. The node must be in 'configured' or 'configuring' state in order to unconfigure it.":                25,
	"Error updating registeredServices for node %v in the exchange: %v":                                                               70,
	"Error updating retry start state for service instance %v in dadabase. %v":                                                        123,
	"Error verifiying exchange version. error: %v":                                                                                    12,
	"Expression: %v is not valid":                                                                                                     136,
	"Expression: %v should contain valid comparison operator - wrong operator %v. Allowed operators: %v, %v, %v, %v, %v, %v, %v, %v":  129,
	"Failed get user input from local db. %v":                                                                                         34,
	"Failed retrying number %v for dependent service %v version %v.":                                                                  121,
	"Failed to downgrade service %v/%v version %v, error: %v":                                                                         114,
	"Failed to find preferences for service %v/%v from the local user input, error: %v":                                               35,
	"Failed to get a list of parent containers for service retry for %v. %v":                                                          192,
	"Failed to get the service retry count for %v version %v. %v":                                                                     122,
	"Failed to restoring the network connection with the parents for service %v. %v":                                                  193,
	"Failed to upgrade service %v/%v from version %v to version %v, error: %v":                                                        110,
	"Image loaded for %v/%v.":                                                                                                         71,
	"Image loaded for service %v/%v.":                                                                                                 72,
	"Input error for node unregistration. %v is an incorrect value for block":                                                         28,
	"Input error for node unregistration. %v is an incorrect value for deepClean":                                                     27,
	"Input error for node unregistration. %v is an incorrect value for removeNode":                                                    26,
	"Input version string %v or %v is not a valid single version string.":                                                             157,
	"Logical operator %v is not valid, expecting AND, OR, &&, ||":                                                                     126,
	"Name, or Org is empty string.":                                                                                                   180,
	"New node policy: %v":                                                                                                             40,
	"New node user input: %v":                                                                                                         42,
	"No node user input to detele":                                                                                                    43,
	"Node could not verify the agreement %v with the consumer. Will cancel it":                                                        178,
	"Node heartbeat failed for node %v/%v. Error: %v":                                                                                 170,
	"Node heartbeat restored for node %v/%v.":                                                                                         171,
	"Node is offline. Logging of periodic offline error messages will be curtailed until connection is restored":                      179,
	"Node policy updated with the exchange copy: %v":                                                                                  175,
	"Node received Cancel message for %v/%v from agbot %v.":                                                                           83,
	"Node received Proposal message for service %v/%v from the agbot %v.":                                                             149,
	"Node rejected the proposal for service %v/%v.":                                                                                   150,
	"Node state transition from '%v' to '%v' is not supported.":                                                                       33,
	"Node unregistration complete for node %v.":                                                                                       23,
	"Node user input updated with the exchange copy. The changed user inputs are: %v":                                                 177,
	"Property %s has invalid property type %s. Allowed property types are: version, string, int, boolean, float, and list of string.": 160,
	"Property %s has invalid value type %T":                                                                                           165,
	"Property %s with value %v is not a valid verion string":                                                                          164,
	"Property must include a name and a value: %v":                                                                                    159,
	"Property value is of type %T, expected type %s":                                                                                  161,
	"ReplyAck indicated that the agbot did not want to pursue the agreement for %v. Node will cancel the agreement":                   82,
	"Service containers for %v started.":                                                                                              94,
	"Start agreement-less service %v/%v.":                                                                                             102,
	"Start changing service configuration state to %v for %v for the node.":                                                           52,
	"Start cleaning up service %v because agreement %v ended.":                                                                        99,
	"Start dependent services for %v/%v.":                                                                                             96,
	"Start downgrading service %v/%v version %v because service failed to start.":                                                     112,
	"Start downgrading service %v/%v version %v because service for agreement failed to start.":                                       111,
	"Start downgrading service %v/%v version %v because upgrade failed.":                                                              113,
	"Start node configuration/registration for node %v.":                                                                              19,
	"Start node unregistration.":                                                                                                      22,
	"Start policy advertising with the exchange for service %v/%v.":                                                                   167,
	"Start retrying number %v for dependent service %v version %v because service failed.":                                            120,
	"Start service auto configuration for %v/%v.":                                                                                     46,
	"Start service configuration with user input for %v/%v.":                                                                          45,
	"Start terminating agreement for %v. Termination reason: %v":                                                                      75,
	"Start updating node %v.":                                                                                                         20,
	"Start upgrading service %v/%v from version %v to version %v.":                                                                    108,
	"Start workload service for %v/%v.":                                                                                               92,
	"The constraint expression: %v is type %T, but is expected to be an array of strings":                                             124,
	"The serviceVersions array is empty.":                                                                                             181,
	"Unable to advertise policies with exchange for service %v/%v, error: %v":                                                         168,
	"Unable to read node object from database, error %v":                                                                              29,
	"Unable to read node object from the local database. %v":                                                                          173,
	"Unable to read policy file %v for service %v, error: %v":                                                                         166,
	"Unable to retrieve agreement %v from database for Cancel message, error %v":                                                      57,
	"Unable to retrieve agreement %v from database for DataReceived message, error %v":                                                59,
	"Unable to retrieve agreement %v from database for MeteringNotification message, error %v":                                        56,
	"Unable to retrieve agreement %v from database for ReplyAck message, error %v":                                                    58,
	"Unable to retrieve the service configuration state for node resource %v from the exchange, error %v":                             68,
	"Unable to retrieve unarchived agreements from database. %v":                                                                      60,
	"Unable to start agreement-less service %v/%v, error %v":                                                                          104,
	"Unable to start agreement-less service %v/%v, local service definition not found":                                                107,
	"Unable to start agreement-less services, error searching for pattern %v in exchange, error: %v":                                  105,
	"Unable to start agreement-less services, pattern %v not found in exchange":                                                       106,
	"Unable to sync the local node policy with the exchange copy. Error: %v":                                                          174,
	"Unable to sync the local node user input with the exchange copy. Error: %v":                                                      176,
	"Value %v of property %s is not a valid string. Please define type or change value to a string.":                                  163,
	"Value %v of property %s is not an integer type":                                                                                  162,
	"Variable %v is missing in the service configuration for %v/%v. It may cause agreement not formed if the business policy does not contain the setting for the missing variable.": 49,
	"Version_Expression: %v does not begin with an inclusion or exclusion directive.":                                                                                                154,
	"Version_Expression: %v does not end with an inclusion or exclusion directive.":                                                                                                  155,
	"Version_Expression: %v is not a valid version string.":                                                                                                                          153,
	"Version_Expression: Incorrect number of versions in expression: %v.":                                                                                                            156,
	"Version_Expression: Whitespace is not permitted in %v.":                                                                                                                         152,
	"Workload destroyed for %v":                                                                  93,
	"Workload service containers for %v/%v are up and running.":                                  78,
	"found %v token(s), expecting 3 in an expression %v, expected form is <property> == <value>": 127,
	"found %v token(s), expecting 3 in an expression %v, expected form is expression with 3 tokens: <property> <operator> <value> in constraint expression": 128,
	"properties contains an invalid property: %v":                                      158,
	"received error demarshalling TsAndCs for agrement %v, %v":                         148,
	"unable to close MMS API certificate file %v, error %v":                            143,
	"unable to close MMS API certificate private key file %v, error %v":                146,
	"unable to convert policy constraint %v into internal format, error %v":            125,
	"unable to create MMS API certificate, error %v":                                   140,
	"unable to encode MMS API certificate private key to file %v, error %v":            145,
	"unable to encode MMS API certificate to file %v, error %v":                        142,
	"unable to generate private key for MMS API certificate, error %v":                 139,
	"unable to generate random number for MMS API certificate serial number, error %v": 138,
	"unable to make directory for self signed MMS API certificate, error %v":           137,
	"unable to read node policy from the local database. %v":                           172,
	"unable to write MMS API certificate private key to file %v, error %v":             144,
	"unable to write MMS API certificate to file %v, error %v":                         141,
}

var deIndex = []uint32{ // 195 elements
	// Entry 0 - 1F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 20 - 3F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 40 - 5F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 60 - 7F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 80 - 9F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry A0 - BF
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry C0 - DF
	0x00000000, 0x00000000, 0x00000000,
} // Size: 804 bytes

const deData string = ""

var enIndex = []uint32{ // 195 elements
	// Entry 0 - 1F
	0x00000000, 0x0000002a, 0x00000056, 0x000000d7,
	0x0000015f, 0x000001cc, 0x0000023e, 0x000002d1,
	0x00000355, 0x000003ce, 0x0000040d, 0x00000431,
	0x00000455, 0x00000485, 0x000004b7, 0x000004dc,
	0x00000501, 0x0000052a, 0x00000553, 0x0000057b,
	0x000005b1, 0x000005cc, 0x000005ec, 0x00000607,
	0x00000634, 0x0000067a, 0x000006eb, 0x0000073b,
	0x0000078a, 0x000007d5, 0x0000080b, 0x00000855,
	// Entry 20 - 3F
	0x0000089b, 0x00000917, 0x00000957, 0x00000982,
	0x000009dd, 0x00000a13, 0x00000a4c, 0x00000a7c,
	0x00000ab6, 0x00000acd, 0x00000ae1, 0x00000afc,
	0x00000b19, 0x00000b35, 0x00000b72, 0x00000ba4,
	0x00000bd4, 0x00000c09, 0x00000cc1, 0x00000ce8,
	0x00000d1e, 0x00000d6a, 0x00000db9, 0x00000def,
	0x00000e2b, 0x00000e8a, 0x00000edb, 0x00000f2e,
	0x00000f85, 0x00000fc3, 0x00001000, 0x00001037,
	// Entry 40 - 5F
	0x0000109b, 0x000010e1, 0x00001124, 0x00001158,
	0x000011ad, 0x00001217, 0x0000124c, 0x00001294,
	0x000012b2, 0x000012d8, 0x000012fd, 0x0000132a,
	0x0000136b, 0x000013ab, 0x000013f2, 0x00001432,
	0x00001476, 0x000014b9, 0x00001507, 0x00001578,
	0x000015b7, 0x000015e8, 0x0000160f, 0x00001644,
	0x0000166f, 0x000016a9, 0x000016d9, 0x00001708,
	0x0000172d, 0x00001755, 0x00001772, 0x00001798,
	// Entry 60 - 7F
	0x000017c9, 0x000017f3, 0x00001837, 0x0000188c,
	0x000018cb, 0x0000190a, 0x00001940, 0x0000196a,
	0x000019b3, 0x000019f3, 0x00001a58, 0x00001aa5,
	0x00001afc, 0x00001b45, 0x00001b91, 0x00001be9,
	0x00001c4c, 0x00001ca1, 0x00001ced, 0x00001d31,
	0x00001d7f, 0x00001dee, 0x00001e37, 0x00001e8e,
	0x00001ec9, 0x00001f27, 0x00001f6f, 0x00001fb4,
	0x00002003, 0x0000205d, 0x000020a9, 0x000020e8,
	// Entry 80 - 9F
	0x00002149, 0x000021e5, 0x00002283, 0x000022c8,
	0x0000230d, 0x00002356, 0x0000239a, 0x000023e0,
	0x0000242a, 0x00002449, 0x00002493, 0x000024e7,
	0x0000252b, 0x0000255d, 0x0000259c, 0x000025dc,
	0x00002618, 0x00002663, 0x000026af, 0x000026f7,
	0x00002730, 0x0000276f, 0x000027bc, 0x000027f0,
	0x0000282e, 0x00002868, 0x000028a1, 0x000028f4,
	0x00002945, 0x0000298c, 0x000029d6, 0x00002a05,
	// Entry A0 - BF
	0x00002a35, 0x00002abb, 0x00002af0, 0x00002b25,
	0x00002b8a, 0x00002bc7, 0x00002bf3, 0x00002c34,
	0x00002c78, 0x00002cc9, 0x00002d10, 0x00002d49,
	0x00002d77, 0x00002db1, 0x00002deb, 0x00002e35,
	0x00002e67, 0x00002eb5, 0x00002f08, 0x00002f54,
	0x00002fbf, 0x00002fdd, 0x00003001, 0x00003048,
	0x0000309e, 0x000030e6, 0x00003129, 0x00003163,
	0x000031ba, 0x000031db, 0x00003210, 0x00003248,
	// Entry C0 - DF
	0x000032a3, 0x000032f0, 0x00003345,
} // Size: 804 bytes

const enData string = "" + // Size: 13125 bytes
	"\x02Error parsing the selections %[1]v. %[2]v\x02Error getting %[1]v for" +
	" output, error %[2]v\x02Error parsing input for node configuration/regis" +
	"tration. Input body couldn't be deserialized to node object: %[1]v, erro" +
	"r: %[2]v\x02Error parsing input for node configuration/registration. Inp" +
	"ut body couldn't be deserialized to configstate object: %[1]v, error: %[" +
	"2]v\x02Error parsing input for node update. Input body couldn't be deser" +
	"ialized to node object: %[1]v, error: %[2]v\x02Error parsing input for n" +
	"ode policy. Input body could not be deserialized as a policy object: %[1" +
	"]v, error: %[2]v\x02Error parsing input for node policy patch. Input bod" +
	"y could not be deserialized into a Constraint Expression or Property Lis" +
	"t: %[1]v, error: %[2]v\x02Error parsing input for node policy patch. Inp" +
	"ut body did not contain a Constraint Expression or Property List: %[1]v," +
	" error: %[2]v\x02Error parsing input for node user input. Input body cou" +
	"ld not be deserialized as a UserInput object: %[1]v, error: %[2]v\x02Err" +
	"or in node configuration/registration for node %[1]v. %[2]v\x02Error in " +
	"updating node %[1]v. %[2]v\x02Error in node unregistration. %[1]v\x02Err" +
	"or verifiying exchange version. error: %[1]v\x02Error in creating or rep" +
	"lacing node policy. %[1]v\x02Error in patching node policy. %[1]v\x02Err" +
	"or in deleting node policy. %[1]v\x02Error in updating node user input. " +
	"%[1]v\x02Error in patching node user input. %[1]v\x02Error in deleting n" +
	"ode userinput. %[1]v\x02Start node configuration/registration for node %" +
	"[1]v.\x02Start updating node %[1]v.\x02Complete node update for %[1]v." +
	"\x02Start node unregistration.\x02Node unregistration complete for node " +
	"%[1]v.\x02Error unregistring the node. The node is not found from the da" +
	"tabase.\x02Error unregistring the node. The node must be in 'configured'" +
	" or 'configuring' state in order to unconfigure it.\x02Input error for n" +
	"ode unregistration. %[1]v is an incorrect value for removeNode\x02Input " +
	"error for node unregistration. %[1]v is an incorrect value for deepClean" +
	"\x02Input error for node unregistration. %[1]v is an incorrect value for" +
	" block\x02Unable to read node object from database, error %[1]v\x02Error" +
	" saving new node config state (unconfiguring) in the database: %[1]v\x02" +
	"Error in node configuration. The node is not found from the database." +
	"\x02Error in node configuration. The node must be in 'configured' or 'co" +
	"nfiguring' state in order to change the state to %[1]v.\x02Node state tr" +
	"ansition from '%[1]v' to '%[2]v' is not supported.\x02Failed get user in" +
	"put from local db. %[1]v\x02Failed to find preferences for service %[1]v" +
	"/%[2]v from the local user input, error: %[3]v\x02Error saving new node " +
	"config state to database: %[1]v\x02Complete node configuration/registrat" +
	"ion for node %[1]v.\x02Error in service configuration for %[1]v. %[2]v" +
	"\x02Error getting service references for pattern %[1]v. %[2]v\x02New nod" +
	"e policy: %[1]v\x02Deleted node policy\x02New node user input: %[1]v\x02" +
	"No node user input to detele\x02Deleted all node user input\x02Start ser" +
	"vice configuration with user input for %[1]v/%[2]v.\x02Start service aut" +
	"o configuration for %[1]v/%[2]v.\x02Complete service configuration for %" +
	"[1]v/%[2]v.\x02Complete service auto configuration for %[1]v/%[2]v.\x02V" +
	"ariable %[1]v is missing in the service configuration for %[2]v/%[3]v. I" +
	"t may cause agreement not formed if the business policy does not contain" +
	" the setting for the missing variable.\x02Error configuring service %[1]" +
	"v. %[2]v\x02Error changing service configstate %[1]v, error %[2]v\x02Sta" +
	"rt changing service configuration state to %[1]v for %[2]v for the node." +
	"\x02Complete changing service configuration state to %[1]v for %[2]v for" +
	" the node.\x02Error converting the selections into Selectors: %[1]v\x02E" +
	"rror retrieving agreement %[1]v from database, error %[2]v\x02Unable to " +
	"retrieve agreement %[1]v from database for MeteringNotification message," +
	" error %[2]v\x02Unable to retrieve agreement %[1]v from database for Can" +
	"cel message, error %[2]v\x02Unable to retrieve agreement %[1]v from data" +
	"base for ReplyAck message, error %[2]v\x02Unable to retrieve agreement %" +
	"[1]v from database for DataReceived message, error %[2]v\x02Unable to re" +
	"trieve unarchived agreements from database. %[1]v\x02Error marking agree" +
	"ment %[1]v terminated in database: %[2]v.\x02Error getting service defin" +
	"itions %[1]v from db. %[2]v\x02Error retrieving all service instances fr" +
	"om datavase for %[1]v/%[2]v version %[3]v key %[4]v. %[5]v\x02Error retr" +
	"ieving all service instances from database for %[1]v. %[2]v\x02Error ret" +
	"rieving all service instances from database, error: %[1]v\x02Error getti" +
	"ng service instance %[1]v from db. %[2]v\x02Error retrieving matching ag" +
	"reements from database for workloads %[1]v. Error: %[2]v\x02Unable to re" +
	"trieve the service configuration state for node resource %[1]v from the " +
	"exchange, error %[2]v\x02Error retrieving node %[1]v from the exchange: " +
	"%[2]v\x02Error updating registeredServices for node %[1]v in the exchang" +
	"e: %[2]v\x02Image loaded for %[1]v/%[2]v.\x02Image loaded for service %[" +
	"1]v/%[2]v.\x02Error loading image for %[1]v/%[2]v.\x02Error loading imag" +
	"e for service %[1]v/%[2]v.\x02Start terminating agreement for %[1]v. Ter" +
	"mination reason: %[2]v\x02Agreement reached for service %[1]v. The agree" +
	"ment id is %[2]v.\x02Agreement for %[1]v no longer valid on the agbot. N" +
	"ode will cancel it.\x02Workload service containers for %[1]v/%[2]v are u" +
	"p and running.\x02Complete terminating agreement for %[1]v. Termination " +
	"reason: %[2]v\x02Error deleting agreement for %[1]v in exchange: %[2]v. " +
	"Will retry.\x02Encountered error for AgreementVerification for %[1]v wit" +
	"h agbot, error %[2]v\x02ReplyAck indicated that the agbot did not want t" +
	"o pursue the agreement for %[1]v. Node will cancel the agreement\x02Node" +
	" received Cancel message for %[1]v/%[2]v from agbot %[3]v.\x02Error hand" +
	"ling ReplyAck message for %[1]v. %[2]v\x02Error handling ReplyAck messag" +
	"e. %[1]v\x02Error handling DataReceived message for %[1]v. %[2]v\x02Erro" +
	"r handling DataReceived message. %[1]v\x02Error handling MeterNotificati" +
	"on message for %[1]v. %[2]v\x02Error handling MeterNotification message." +
	" %[1]v\x02Error handling Cancel message for %[1]v. %[2]v\x02Error handli" +
	"ng Cancel message. %[1]v\x02Start workload service for %[1]v/%[2]v.\x02W" +
	"orkload destroyed for %[1]v\x02Service containers for %[1]v started.\x02" +
	"Complete cleaning up the service instance %[1]v.\x02Start dependent serv" +
	"ices for %[1]v/%[2]v.\x02Encountered error starting dependen services fo" +
	"r %[1]v/%[2]v. %[3]v\x02Error starting dependen service %[1]v/%[2]v vers" +
	"ion %[3]v for agreement %[4]v. %[5]v\x02Start cleaning up service %[1]v " +
	"because agreement %[2]v ended.\x02Error starting service %[1]v/%[2]v ver" +
	"sion %[3]v, error: %[4]v\x02Error getting all the services from agreemen" +
	"ts: %[1]v\x02Start agreement-less service %[1]v/%[2]v.\x02Complete start" +
	"ing agreement-less service %[1]v/%[2]v and its dependents.\x02Unable to " +
	"start agreement-less service %[1]v/%[2]v, error %[3]v\x02Unable to start" +
	" agreement-less services, error searching for pattern %[1]v in exchange," +
	" error: %[2]v\x02Unable to start agreement-less services, pattern %[1]v " +
	"not found in exchange\x02Unable to start agreement-less service %[1]v/%[" +
	"2]v, local service definition not found\x02Start upgrading service %[1]v" +
	"/%[2]v from version %[3]v to version %[4]v.\x02Complete upgrading servic" +
	"e %[1]v/%[2]v from version %[3]v to version %[4]v.\x02Failed to upgrade " +
	"service %[1]v/%[2]v from version %[3]v to version %[4]v, error: %[5]v" +
	"\x02Start downgrading service %[1]v/%[2]v version %[3]v because service " +
	"for agreement failed to start.\x02Start downgrading service %[1]v/%[2]v " +
	"version %[3]v because service failed to start.\x02Start downgrading serv" +
	"ice %[1]v/%[2]v version %[3]v because upgrade failed.\x02Failed to downg" +
	"rade service %[1]v/%[2]v version %[3]v, error: %[4]v\x02Complete downgra" +
	"ding service %[1]v/%[2]v from version %[3]v to version %[4]v.\x02Error f" +
	"inding the new service definition to downgrade to for %[1]v/%[2]v versio" +
	"n %[3]v key %[4]v. error: %[5]v\x02Could not find lower version to downg" +
	"rade for %[1]v/%[2]v version %[3]v.\x02Error downgrading service %[1]v/%" +
	"[2]v from version %[3]v to version %[4]v. Eror: %[5]v\x02Error downgradi" +
	"ng service %[1]v/%[2]v version %[3]v. %[4]v\x02Start retrying number %[1" +
	"]v for dependent service %[2]v version %[3]v because service failed.\x02" +
	"Failed retrying number %[1]v for dependent service %[2]v version %[3]v." +
	"\x02Failed to get the service retry count for %[1]v version %[2]v. %[3]v" +
	"\x02Error updating retry start state for service instance %[1]v in dadab" +
	"ase. %[2]v\x02The constraint expression: %[1]v is type %[2]T, but is exp" +
	"ected to be an array of strings\x02unable to convert policy constraint %" +
	"[1]v into internal format, error %[2]v\x02Logical operator %[1]v is not " +
	"valid, expecting AND, OR, &&, ||\x02found %[1]v token(s), expecting 3 in" +
	" an expression %[2]v, expected form is <property> == <value>\x02found %[" +
	"1]v token(s), expecting 3 in an expression %[2]v, expected form is expre" +
	"ssion with 3 tokens: <property> <operator> <value> in constraint express" +
	"ion\x02Expression: %[1]v should contain valid comparison operator - wron" +
	"g operator %[2]v. Allowed operators: %[3]v, %[4]v, %[5]v, %[6]v, %[7]v, " +
	"%[8]v, %[9]v, %[10]v\x02Comparison operator: %[1]v is not supported for " +
	"numeric value: %[2]v\x02Comparison operator: %[1]v is not supported for " +
	"boolean value: %[2]v\x02Comparison operator: %[1]v is not supported for " +
	"string list value: %[2]v\x02Comparison operator: %[1]v is not supported " +
	"for string value: %[2]v\x02Comparison operator: %[1]v is not supported f" +
	"or single version: %[2]v\x02Comparison operator: %[1]v is not supported " +
	"for version expression: %[2]v\x02Expression: %[1]v is not valid\x02unabl" +
	"e to make directory for self signed MMS API certificate, error %[1]v\x02" +
	"unable to generate random number for MMS API certificate serial number, " +
	"error %[1]v\x02unable to generate private key for MMS API certificate, e" +
	"rror %[1]v\x02unable to create MMS API certificate, error %[1]v\x02unabl" +
	"e to write MMS API certificate to file %[1]v, error %[2]v\x02unable to e" +
	"ncode MMS API certificate to file %[1]v, error %[2]v\x02unable to close " +
	"MMS API certificate file %[1]v, error %[2]v\x02unable to write MMS API c" +
	"ertificate private key to file %[1]v, error %[2]v\x02unable to encode MM" +
	"S API certificate private key to file %[1]v, error %[2]v\x02unable to cl" +
	"ose MMS API certificate private key file %[1]v, error %[2]v\x02Agreement" +
	" %[1]v already exists, ignoring proposal: %[2]v\x02received error demars" +
	"halling TsAndCs for agrement %[1]v, %[2]v\x02Node received Proposal mess" +
	"age for service %[1]v/%[2]v from the agbot %[3]v.\x02Node rejected the p" +
	"roposal for service %[1]v/%[2]v.\x02Error handling proposal for service " +
	"%[1]v/%[2]v. Error: %[3]v\x02Version_Expression: Whitespace is not permi" +
	"tted in %[1]v.\x02Version_Expression: %[1]v is not a valid version strin" +
	"g.\x02Version_Expression: %[1]v does not begin with an inclusion or excl" +
	"usion directive.\x02Version_Expression: %[1]v does not end with an inclu" +
	"sion or exclusion directive.\x02Version_Expression: Incorrect number of " +
	"versions in expression: %[1]v.\x02Input version string %[1]v or %[2]v is" +
	" not a valid single version string.\x02properties contains an invalid pr" +
	"operty: %[1]v\x02Property must include a name and a value: %[1]v\x02Prop" +
	"erty %[1]s has invalid property type %[2]s. Allowed property types are: " +
	"version, string, int, boolean, float, and list of string.\x02Property va" +
	"lue is of type %[1]T, expected type %[2]s\x02Value %[1]v of property %[2" +
	"]s is not an integer type\x02Value %[1]v of property %[2]s is not a vali" +
	"d string. Please define type or change value to a string.\x02Property %[" +
	"1]s with value %[2]v is not a valid verion string\x02Property %[1]s has " +
	"invalid value type %[2]T\x02Unable to read policy file %[1]v for service" +
	" %[2]v, error: %[3]v\x02Start policy advertising with the exchange for s" +
	"ervice %[1]v/%[2]v.\x02Unable to advertise policies with exchange for se" +
	"rvice %[1]v/%[2]v, error: %[3]v\x02Complete policy advertising with the " +
	"exchange for service %[1]v/%[2]v.\x02Node heartbeat failed for node %[1]" +
	"v/%[2]v. Error: %[3]v\x02Node heartbeat restored for node %[1]v/%[2]v." +
	"\x02unable to read node policy from the local database. %[1]v\x02Unable " +
	"to read node object from the local database. %[1]v\x02Unable to sync the" +
	" local node policy with the exchange copy. Error: %[1]v\x02Node policy u" +
	"pdated with the exchange copy: %[1]v\x02Unable to sync the local node us" +
	"er input with the exchange copy. Error: %[1]v\x02Node user input updated" +
	" with the exchange copy. The changed user inputs are: %[1]v\x02Node coul" +
	"d not verify the agreement %[1]v with the consumer. Will cancel it\x02No" +
	"de is offline. Logging of periodic offline error messages will be curtai" +
	"led until connection is restored\x02Name, or Org is empty string.\x02The" +
	" serviceVersions array is empty.\x02Deployment config %[1]v contains uns" +
	"upported capability for a workload\x02Deployment config %[1]v contains u" +
	"nsupported capability for infrastructure container.\x02Deployment config" +
	" %[1]v contains unsupported bind for a workload, %[2]v\x02Deployment con" +
	"fig %[1]v contains unsupported bind for %[2]v, %[3]v\x02Error Unmarshall" +
	"ing deployment string %[1]v, error: %[2]v\x02Error Unmarshalling deploym" +
	"ent override string %[1]v for agreement %[2]v, error: %[3]v\x02Error sta" +
	"rting containers: %[1]v\x02Error starting containers for agreement %[1]v" +
	": %[2]v\x02Error restarting containers for agreements %[1]v: %[2]v\x02Er" +
	"ror cleaning up old containers before starting up new containers for %[1" +
	"]v. Error: %[2]v\x02Failed to get a list of parent containers for servic" +
	"e retry for %[1]v. %[2]v\x02Failed to restoring the network connection w" +
	"ith the parents for service %[1]v. %[2]v"

var esIndex = []uint32{ // 195 elements
	// Entry 0 - 1F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 20 - 3F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 40 - 5F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 60 - 7F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 80 - 9F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry A0 - BF
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry C0 - DF
	0x00000000, 0x00000000, 0x00000000,
} // Size: 804 bytes

const esData string = ""

var frIndex = []uint32{ // 195 elements
	// Entry 0 - 1F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 20 - 3F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 40 - 5F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 60 - 7F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 80 - 9F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry A0 - BF
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry C0 - DF
	0x00000000, 0x00000000, 0x00000000,
} // Size: 804 bytes

const frData string = ""

var itIndex = []uint32{ // 195 elements
	// Entry 0 - 1F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 20 - 3F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 40 - 5F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 60 - 7F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 80 - 9F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry A0 - BF
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry C0 - DF
	0x00000000, 0x00000000, 0x00000000,
} // Size: 804 bytes

const itData string = ""

var jaIndex = []uint32{ // 195 elements
	// Entry 0 - 1F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 20 - 3F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 40 - 5F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 60 - 7F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 80 - 9F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry A0 - BF
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry C0 - DF
	0x00000000, 0x00000000, 0x00000000,
} // Size: 804 bytes

const jaData string = ""

var koIndex = []uint32{ // 195 elements
	// Entry 0 - 1F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 20 - 3F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 40 - 5F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 60 - 7F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 80 - 9F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry A0 - BF
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry C0 - DF
	0x00000000, 0x00000000, 0x00000000,
} // Size: 804 bytes

const koData string = ""

var pt_BRIndex = []uint32{ // 195 elements
	// Entry 0 - 1F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 20 - 3F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 40 - 5F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 60 - 7F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 80 - 9F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry A0 - BF
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry C0 - DF
	0x00000000, 0x00000000, 0x00000000,
} // Size: 804 bytes

const pt_BRData string = ""

var zh_CNIndex = []uint32{ // 195 elements
	// Entry 0 - 1F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 20 - 3F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 40 - 5F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000025, 0x00000025, 0x00000025, 0x00000025,
	0x00000025, 0x00000063, 0x00000063, 0x00000096,
	0x00000096, 0x00000096, 0x00000096, 0x00000096,
	0x00000096, 0x00000096, 0x00000096, 0x00000096,
	0x00000096, 0x00000096, 0x00000096, 0x00000096,
	0x00000096, 0x00000096, 0x00000096, 0x000000bd,
	// Entry 60 - 7F
	0x000000bd, 0x000000bd, 0x000000bd, 0x000000bd,
	0x000000bd, 0x000000bd, 0x000000bd, 0x000000bd,
	0x000000bd, 0x000000bd, 0x000000bd, 0x000000bd,
	0x000000bd, 0x000000bd, 0x000000bd, 0x000000bd,
	0x000000bd, 0x000000bd, 0x000000bd, 0x000000bd,
	0x000000bd, 0x000000bd, 0x000000bd, 0x000000bd,
	0x000000bd, 0x000000bd, 0x000000bd, 0x000000bd,
	0x000000bd, 0x000000bd, 0x000000bd, 0x000000bd,
	// Entry 80 - 9F
	0x000000bd, 0x000000bd, 0x000000bd, 0x000000bd,
	0x000000bd, 0x000000bd, 0x000000bd, 0x000000bd,
	0x000000bd, 0x000000bd, 0x000000bd, 0x000000bd,
	0x000000bd, 0x000000bd, 0x000000bd, 0x000000bd,
	0x000000bd, 0x000000bd, 0x000000bd, 0x000000bd,
	0x000000bd, 0x000000bd, 0x000000bd, 0x000000bd,
	0x000000bd, 0x000000bd, 0x000000bd, 0x000000bd,
	0x000000bd, 0x000000bd, 0x000000bd, 0x000000bd,
	// Entry A0 - BF
	0x000000bd, 0x000000bd, 0x000000bd, 0x000000bd,
	0x000000bd, 0x000000bd, 0x000000bd, 0x000000bd,
	0x000000bd, 0x000000bd, 0x000000bd, 0x000000bd,
	0x000000bd, 0x000000bd, 0x000000bd, 0x000000bd,
	0x000000bd, 0x000000bd, 0x000000bd, 0x000000bd,
	0x000000bd, 0x000000bd, 0x000000bd, 0x000000bd,
	0x000000bd, 0x000000bd, 0x000000bd, 0x000000bd,
	0x000000bd, 0x000000bd, 0x000000bd, 0x000000bd,
	// Entry C0 - DF
	0x000000bd, 0x000000bd, 0x000000bd,
} // Size: 804 bytes

const zh_CNData string = "" + // Size: 189 bytes
	"\x02%[1]v/%[2]v 的程序已经载入。\x02为%[1]v制定的协议已经达成，协议号为：%[2]v。\x02%[1]v/%[2]v的作" +
	"业服务器已经开始运行。\x02%[1]v的服务器已经开始运行。"

var zh_TWIndex = []uint32{ // 195 elements
	// Entry 0 - 1F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 20 - 3F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 40 - 5F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 60 - 7F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 80 - 9F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry A0 - BF
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry C0 - DF
	0x00000000, 0x00000000, 0x00000000,
} // Size: 804 bytes

const zh_TWData string = ""

// Total table size 21354 bytes (20KiB); checksum: FB9A1108
