FROM ##from_image##
MAINTAINER dave booz <booz@us.ibm.com>

ENV DEBIAN_FRONTEND=noninteractive

ENV ARCH=##arch##
ENV GOPATH=/go
ENV GOROOT=/usr/local/go
ENV SL_USERNAME=##slusername##
ENV SL_API_KEY=##slapikey##

# install build tools (gcc is required to build some docker deps)
RUN apt-get update && apt-get install -y git-core make gcc curl vim python-pip

# install python stuff so that we can get swift upload working
RUN pip install virtualenv
RUN pip install python-swiftclient
WORKDIR /tmp
RUN virtualenv venv

# "go get" needs to use SSH instead of HTTPS to download private deps
RUN git config --global url.ssh://git@repo.hovitos.engineering:10022/.insteadOf https://repo.hovitos.engineering/

RUN curl -s ##golang_url## | tar zx -C /usr/local

# copy creds, configs, etc. to fs before build steps
ADD docker-bld /docker
RUN cp -vfa /docker/fs/root/. /root/
RUN cp -vfa /docker/fs/usr/. /usr/

RUN chmod -R 600 /root/.ssh/* && chown -R root /root/.ssh

ENV PATH="$GOPATH/bin:$GOROOT/bin:$PATH"
RUN go get -u github.com/kardianos/govendor
