#!/bin/bash

# copy the out.gotext.json files from locales and cli/locales to i18n_translation directory
cp $PKGPATH/locales/en/out.gotext.json $PKGPATH/i18n_translation/original/anax.out.gotext.json.auto
cp $PKGPATH/cli/locales/en/out.gotext.json $PKGPATH/i18n_translation/original/hzn.out.gotext.json.auto

# remove unnecessary fields for translation process
cat $PKGPATH/i18n_translation/original/anax.out.gotext.json.auto | jq '.messages | del(.[].placeholders) | del(.[].id) | del(.[].translatorComment) | del(.[].fuzzy) ' | sed 's/"message":/"id":/g' > $PKGPATH/i18n_translation/anax.out.gotext.json
cat $PKGPATH/i18n_translation/original/hzn.out.gotext.json.auto  | jq '.messages | del(.[].placeholders) | del(.[].id) | del(.[].translatorComment) | del(.[].fuzzy) ' | sed 's/"message":/"id":/g' > $PKGPATH/i18n_translation/hzn.out.gotext.json
 
