#!/bin/bash

if [ -f /etc/os-release ];then
	. /etc/os-release;
	DISTRO=$ID;
	VER=$VERSION_ID;
elif type lsb_release >/dev/null 2>&1;then
	DISTRO=$(lsb_release -si);
	VER=$(lsb_release -sr);
elif [ -f /etc/lsb-release ];then
	. /etc/lsb-release;
	DISTRO=$DISTRIB_ID;VER=$DISTRIB_RELEASE;
fi

# get rid of version's fraction (major releases make sense)
VER=${VER%%.*}

if [[ "$DISTRO" == fedora && $VER -ge 27 ]];then
	echo true;
elif [[ $DISTRO =~ ^(centos|rhel)$ && $VER -ge 7 ]];then
	echo true;
else
	echo false;
fi